### ISSUE TITLE
都已经 Xcode9了，还用 PCH 吗

### ISSUE THREAD

**Issue by josercc** [maltsugar/AwesomTemplate#1]
在 Xcode8苹果已经不支持 PCH 的自动提示了 目的就是让开发者忘记 PCH 存在，提高编译速度。虽然不使用 PCH，导入头文件变得很麻烦。但是提高了代码的健壮性，分离性。而且提升了很久之前存在的编译问题。都已经出 Xcode9了，还在用 PCH 就过分了。
目前我们的项目是尽量减掉宏，必要使用宏也不会启动改动造成再次编译。去掉 PCH，全面使用导入头文件进行开发。

**Comment by maltsugar** [comment]
pch还是很方便的，我还是这样用的。不然总感觉少点什么😬

**Comment by josercc** [comment]
苹果慢慢让开发者去掉 PCH

**Comment by maltsugar** [comment]
嗯嗯 你可以不用pch，我很依赖这个，特别是导入头文件，没有pch简直抓狂。等什么时候xcode无法设置pch，或许我才会不用。
